server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: ms-publicaciones-autor
          uri: lb://SERVICIO-PUBLICACIONES
          predicates:
            - Path=/api/v1/autor/**
          filters:
            - StripPrefix=3

        - id: ms-publicaciones-libro
          uri: lb://SERVICIO-PUBLICACIONES
          predicates:
            - Path=/api/v1/libro/**
          filters:
            - StripPrefix=2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
    instance:
      preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

         

